name: Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pest:
    runs-on: ubuntu-22.04

    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: 🧶 Install Node Dependencies
        run: yarn install --frozen-lockfile --no-progress
      - name: 🧱 Build JS Dependencies
        run: yarn build
      - name: 🕵️‍♂️ Run Pest Tests
        run: composer test
